export default {
    GET_TOKEN: 'GET_TOKEN',
    GET_USER: 'GET_USER',
    AUTH_ERROR: 'AUTH_ERROR',
    IS_LOADING: 'IS_LOADING',
    IS_SUBMITTING: 'IS_SUBMITTING',
    FORM_VALIDATION_ERRORS: 'FORM_VALIDATION_ERRORS',
    LOGOUT: 'LOGOUT',
    LOGGED_OUT: 'LOGGED_OUT',
}